// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyn06ACT6euicZ1eJvVIweNpN_Jpkwb3E',
    appId: '1:264308689519:web:2f1d2d5a16bafbc0865b9a',
    messagingSenderId: '264308689519',
    projectId: 'easarkuz',
    authDomain: 'easarkuz.firebaseapp.com',
    storageBucket: 'easarkuz.appspot.com',
    measurementId: 'G-7LGP7ZYCP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXDIzqGlIMCb04sVOw54amSQghjmH2AbU',
    appId: '1:264308689519:android:68e8dfcbc8052849865b9a',
    messagingSenderId: '264308689519',
    projectId: 'easarkuz',
    storageBucket: 'easarkuz.appspot.com',
  );
}
